using UnityEngine;
using System.Collections;

public class MeshCreatorData : MonoBehaviour {
	public string errorMessage = "reinstall the mesh creator package.";
	
	// use this texture for creating the outine
	public Texture2D outlineTexture;
    public float pixelTransparencyThreshold = 255;
	public const float versionNumber = 0.7f;
	
	// settings for what the script will create
	public bool uvWrapMesh = true;
	public bool createEdges = true;
	public bool createBacksidePlane = false;
	
	// stores an automatically created material
	public Material frontMaterial;
	
	// total height, width, and depth of the resulting mesh
	public float meshHeight = 1.0f; 
	public float meshWidth = 1.0f; 
	public float meshDepth = 0.1f;
	
	// set center pivot offset
	public float pivotHeightOffset = 0.0f;
	public float pivotWidthOffset = 0.0f;
	public float pivotDepthOffset = 0.0f;
	
	// store the last pivot offset used so it can be subtracted from next
	public Vector3 lastPivotOffset = Vector3.zero;
	
	// collider settings
	public bool generateCollider = true;
	public bool usePrimitiveCollider = true;
    public bool useAABBCollider = false;
    public int maxNumberBoxes = 20;
    public bool useAutoGeneratedMaterial = false;
	public bool usePhysicMaterial = false;
	public PhysicMaterial physicMaterial;
    public bool setTriggers = false;
	
	public string idNumber = "";
	
	public bool mergeClosePoints = false;
	public float mergeDistance = 0.0f;
	
}
