using UnityEngine;
using System.Collections;

public class MeshCreatorData : MonoBehaviour {
	public Texture2D outlineTexture;
	public Material frontMaterial;
	public float meshHeight = 1.0f; 
	public float meshWidth = 1.0f; 
	public float heightOffset = 0.5f; 
	public float widthOffset = 0.0f; 
	public float meshDepth = 0.1f;
	public bool generateCollider = true;
	public bool usePrimativeCollider = true;
	public float smallestBoxArea = 100.0f;
	public bool useAutoGeneratedMaterial = false;
	public bool usePhysicMaterial = false;
	public PhysicMaterial physicMaterial;
}
