using UnityEngine;
using System.Collections;
using UnityEditor;

public class MeshCreatorWizard : ScriptableWizard {
	
	public Texture2D textureToCreateMeshFrom;
	public bool useDepth;
	public bool withColliders;
	public float xWidth = 1.0f;
	public float yHeight = 1.0f;
	public float zDepth = 1.0f;
	public string gameObjectName = "Mesh Creator Object";
	
	[MenuItem ("GameObject/Create Mesh Object")]
	static void CreateWizard()
	{
		ScriptableWizard.DisplayWizard<MeshCreatorWizard>("Mesh Creator", "Create Mesh");	
	}
	
	// happens when the button is pushed
	void OnWizardCreate()
	{
		// create the new object and set the proper variables		
		GameObject newObject = new GameObject(gameObjectName);
		MeshCreatorData mcd = newObject.AddComponent( "MeshCreatorData" ) as MeshCreatorData;
		
		// set up mcd
		mcd.outlineTexture = textureToCreateMeshFrom;
		mcd.useAutoGeneratedMaterial = true;
		mcd.meshHeight = yHeight;
		mcd.meshWidth = xWidth;
		mcd.meshDepth = zDepth;
		
		// set up the depth options
		if (useDepth)
		{
			mcd.uvWrapMesh = false;
			mcd.createEdges = true;
			mcd.createBacksidePlane = true;
		}
		else
		{
			mcd.uvWrapMesh = false;
			mcd.createEdges = false;
			mcd.createBacksidePlane = false;
		}
		
		// set up the collider options
		if (withColliders)
		{
			mcd.generateCollider = true;
			mcd.usePrimitiveCollider = true;
			mcd.smallestBoxArea = 100.0f;
			mcd.useAutoGeneratedMaterial = true;
			mcd.usePhysicMaterial = false;
			mcd.addRigidBody = true;
		}
		else
		{
			mcd.generateCollider = false;
			mcd.usePrimitiveCollider = false;
			mcd.smallestBoxArea = 100.0f;
			mcd.usePhysicMaterial = false;
			mcd.addRigidBody = false;
		}
		
		// update the mesh
		MeshCreator.UpdateMesh(newObject);
	}
	
	void OnWizardUpdate()
	{
		helpString = "Where is this displayed?";
	}
	
	
	
}
