using UnityEngine;
using System.Collections;
using UnityEditor;


// thanks to Chris Reilly for changing this to EditorWindow from Wizard
public class MeshCreatorWizard : EditorWindow {
	private const float versionNumber = 0.6f;
	private Texture2D gameLabLogo = Resources.Load("games.ucla.logo.small") as Texture2D;
	public Texture2D textureToCreateMeshFrom;
	public bool useDepth;
	public bool withColliders;
	public float xWidth = 1.0f;
	public float yHeight = 1.0f;
	public float zDepth = 1.0f;
	public string gameObjectName = "Mesh Creator Object";
	
	
	// Add menu named "Create Mesh Object" to the GameObject menu
	[MenuItem ("GameObject/Create Mesh Object")]
	
	static void Init () {
		// Get existing open window or if none, make a new one:
		//MeshCreatorWizard window = (MeshCreatorWizard)EditorWindow.GetWindowWithRect( typeof( MeshCreatorWizard ), new Rect( 0,0,500,500 ), true, "Create Mesh Object v" + versionNumber );
		
		MeshCreatorWizard window = (MeshCreatorWizard)EditorWindow.GetWindow( typeof( MeshCreatorWizard ), true, "Create Mesh Object v" + versionNumber );
		
	}
	
	void OnGUI () {
		
		EditorGUIUtility.AddCursorRect( new Rect(10,10,400,150), MouseCursor.Link); 
		
		GUILayout.BeginHorizontal();
			GUILayout.FlexibleSpace();

			
			//game lab logo & link 
			if( GUILayout.Button( gameLabLogo ) ) {
				Application.OpenURL ("http://games.ucla.edu/");	
			}
					
			GUILayout.FlexibleSpace();
				//basic instructions
				GUILayout.Label( "Choose a texture with alpha channel to create a mesh from\nSquare images are recommended.\n\nThen select whether to create depth on the mesh and whether you\nwant colliders for your new mesh.\n\nIndicate size and a game object name and you are good to go.\n\nAdvanced control is available once you create the object.", GUILayout.Width(400) );
			GUILayout.FlexibleSpace();
		GUILayout.EndHorizontal();
				
		GUILayout.BeginHorizontal();
			GUILayout.FlexibleSpace();
			
			GUILayout.BeginVertical();			
			//source texture
			EditorGUILayout.BeginHorizontal();
				GUILayout.Label( "Texture to Create Mesh From", GUILayout.Width(175) );
				textureToCreateMeshFrom = (Texture2D)EditorGUILayout.ObjectField( textureToCreateMeshFrom, typeof(Texture2D), false, GUILayout.Width(175) );
			EditorGUILayout.EndHorizontal();
			
			//use depth?
			GUILayout.BeginHorizontal();
				GUILayout.Label( "Use Depth", GUILayout.Width(175) );
				useDepth = GUILayout.Toggle( useDepth, "" ); 
			GUILayout.EndHorizontal();
			
			//with colliders?
			GUILayout.BeginHorizontal();
				GUILayout.Label( "With Colliders", GUILayout.Width(175) );
				withColliders = GUILayout.Toggle( withColliders, "");
			GUILayout.EndHorizontal();
			
			//width
			EditorGUILayout.BeginHorizontal();
				GUILayout.Label( "Width (X)", GUILayout.Width(175) );
				xWidth = EditorGUILayout.FloatField( xWidth, GUILayout.Width(50) );
			EditorGUILayout.EndHorizontal();
	
			//height
			EditorGUILayout.BeginHorizontal();
				GUILayout.Label( "Height (Y)", GUILayout.Width(175) );
				yHeight = EditorGUILayout.FloatField( yHeight, GUILayout.Width(50) );
			EditorGUILayout.EndHorizontal();
			
			//depth
			EditorGUILayout.BeginHorizontal();
				GUILayout.Label( "Depth (Z)", GUILayout.Width(175) );
				zDepth = EditorGUILayout.FloatField( zDepth, GUILayout.Width(50) );
			EditorGUILayout.EndHorizontal();
			
			//object name
			GUILayout.BeginHorizontal();
				GUILayout.Label( "Game Object Name", GUILayout.Width(175) );
				gameObjectName = GUILayout.TextField( gameObjectName, 50, GUILayout.Width(175) );
			GUILayout.EndHorizontal();
						
			//submit button
			GUILayout.BeginHorizontal();
				GUILayout.FlexibleSpace();
				if( GUILayout.Button( "Create Mesh", GUILayout.Width(100) ) ){
					// create the new object and set the proper variables		
					GameObject newObject = new GameObject(gameObjectName);
					MeshCreatorData mcd = newObject.AddComponent( "MeshCreatorData" ) as MeshCreatorData;
					
					// set up mcd
					mcd.outlineTexture = textureToCreateMeshFrom;
					mcd.useAutoGeneratedMaterial = true;
					mcd.meshHeight = yHeight;
					mcd.meshWidth = xWidth;
					mcd.meshDepth = zDepth;
					
					// set up the depth options
					if (useDepth)
					{
						mcd.uvWrapMesh = false;
						mcd.createEdges = true;
						mcd.createBacksidePlane = true;
					}
					else
					{
						mcd.uvWrapMesh = false;
						mcd.createEdges = false;
						mcd.createBacksidePlane = false;
					}
					
					// set up the collider options
					if (withColliders)
					{
						mcd.generateCollider = true;
						mcd.usePrimitiveCollider = true;
						mcd.smallestBoxArea = 100.0f;
						mcd.useAutoGeneratedMaterial = true;
						mcd.usePhysicMaterial = false;
						mcd.addRigidBody = true;
					}
					else
					{
						mcd.generateCollider = false;
						mcd.usePrimitiveCollider = false;
						mcd.smallestBoxArea = 100.0f;
						mcd.usePhysicMaterial = false;
						mcd.addRigidBody = false;
					}
					
					// update the mesh
					MeshCreator.UpdateMesh(newObject);
					Close();
				}
				GUILayout.FlexibleSpace();
			GUILayout.EndHorizontal();	
			
			GUILayout.EndVertical();
			
		GUILayout.EndHorizontal();
		
	}
}
